In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Saeel's Link
df = pd.read_csv("/content/drive/MyDrive/DS203/EDA.csv")

Link to the dataset: https://drive.google.com/file/d/1L6yQXX1DntaIWhKMIviJnCoM2FIF8prM/view?usp=share_link

If Colab is crashing, we can reduce the size of our dataset by the command below.

In [ ]:
df.drop(df.tail(90000).index, inplace= True)

# **Splitting our Dataset**

In [ ]:
x = df['Description']
y = df['OpenStatus']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer 

In [ ]:
vectorizer = TfidfVectorizer(max_features = 10000) 
x_train_arr = vectorizer.fit_transform(x_train).toarray()  
x_test_arr = vectorizer.transform(x_test).toarray() 

# **Model Building**

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix 

# **Gaussian Naive Bayes Classifier**

In [ ]:
from sklearn.naive_bayes import GaussianNB

Reference: https://scikit-learn.org/stable/modules/naive_bayes.html

In [ ]:
gnb = GaussianNB()

In [ ]:
gnb.fit(x_train_arr, y_train)

GaussianNB()

In [ ]:
# y_predicted_train = gnb.predict(x_train_arr)
y_predicted_test = gnb.predict(x_test_arr)

In [ ]:
# print("Training Accuracy score:",accuracy_score(y_train, y_predicted_train))
print("Testing Accuracy score:",accuracy_score(y_test, y_predicted_test))

Testing Accuracy score: 0.282654820315608


In [ ]:
print('Confusion matrix\n', confusion_matrix(y_test, y_predicted_test))

Confusion matrix
 [[ 312 1644  541  298  513]
 [ 102 1209  213   92   66]
 [  91  895  713  115   95]
 [1110 2292 1125 1879 1099]
 [ 105  178   89  156  150]]


# **Multinomial Naive Bayes Classifier**

In [ ]:
from sklearn.naive_bayes import MultinomialNB

Reference: https://scikit-learn.org/stable/modules/naive_bayes.html

In [ ]:
mnb = MultinomialNB() 

In [ ]:
mnb.fit(x_train_arr, y_train)

MultinomialNB()

In [ ]:
y_predicted_test2 = mnb.predict(x_test_arr)

In [ ]:
print("Testing Accuracy score:",accuracy_score(y_test, y_predicted_test2))

Testing Accuracy score: 0.5900411086062857


In [ ]:
print('Confusion matrix\n', confusion_matrix(y_test, y_predicted_test2))

Confusion matrix
 [[ 421  194   72 2619    2]
 [  87  835   52  708    0]
 [ 100  284  515 1009    1]
 [ 152  118  108 7126    1]
 [  25   12   16  623    2]]
